### ISSUE TITLE
Future maintainance

### ISSUE THREAD

**Issue by sean-hill** [ericholiveira/studio#42]
Hey there,

I'm starting a new large scale project and I thought Studio would be fantastic way to decouple my code and use as my framework with `express`. However, @ericholiveira it's just you contributing to this project, and I'm afraid that a year down the road this won't be supported anymore. I was just curious if you have plans to keep this repo up to date with it's dependencies for the next few years, or if this was just a fun hack project to show how you could use micro services with NodeJS. Thanks man :)

**Comment by ericholiveira** [comment]
Hello @sean-hill . I've been working on studio since Oct/2014 (as you can see here https://github.com/ericholiveira/studio/commits/master?page=11) , it was born from a necessity from the previous company i worked for, im no longer a contributor on that company, but i gathered a lot of their inputs (basically on reducing boilerplate code) and i started to rewrite studio lib to make it easier to reason about, im using studio on the company i work for atm. Just a few (2 or 3) weeks ago i got confident to show it to the world, thats probably the main reason im the only contributor on the project,  because people are just starting to try it, anyway people are starting to get interested on the project and helping me (as you can see here on the cluster plugin https://github.com/ericholiveira/studio-cluster/pulls).  I do have plans to continue with the development of studio, and i have more plans for it (i will add a session of roadmap as soon as i have some time available, but just FYI i do plan to create make studio ready for browser and make browser and server communication transparent, also i plan some kind of studio agent so you can see which services are on and control it from a dashboard or something like this). So i advise you to try it for a while and see if it fits your needs. Im completely open to receive helps (with code, issues, documentation...) from anyone interested.
