### ISSUE TITLE
Retry mechanism

### ISSUE THREAD

**Issue by yarandoo** [ericholiveira/studio#57]
Hey, great framework!

Wondering how would you handle the case when a third party service may be down and you need to keep retrying till it goes up again. 

I see the retry plugin is in memory. What would happen if the instance that is retrying is shutdown(failure or due to a new app deployment). Do you envision any particular way to handle the retrying mechanism in a stateful way? Any recommendations?

Cheers,

**Comment by ericholiveira** [comment]
Hello @yarandoo glad you're enjoying Studio.

So for the first thing, i would advise you against keep retrying forever, because this can lead to a memory leak, imagine that your service keep receiving new calls, and the third part service dont get back, on this scenario you will have an increasing number of services being retried so at some point in the future your system will crash unless the third part service become available.

But, anyway i need to implement some kind of exponential backoff for the time between the retries.

About the problem of the "stateful" retry i can implement the following, the option to add 2 functions to the plugin, one to be called BEFORE the service call (to store data related for that call, like service name and service parameters)  and another to be called after the service success (or after all retries), so you can use this 2 hooks to store this info (in a file or in your database) and after all the retries (or sucess) you can delete this info. This functions can also receive metadata like timestamp, number of attempts, and if it was a success.
To do this, i will also need an extra function which list all "open" retries , this function is going to be called on the startup, and let Studio deals with all the retries.

This solution works for you? I can implement and publish both solutions this week (backoff + stateful retry)

**Comment by yarandoo** [comment]
Guau, thanks for your detailed answer, sounds good! 

Just one question I have is how would you handle the situation where you have multiple instances running the application? As in this case each instance on startup will be initializing its own studio and possibly reading the same pending retries from the store. In this scenario I see that your service call might be executed N times. With N being the number of instances running.


Cheers,

**Comment by ericholiveira** [comment]
So, you can use one of the following solutions:

1- The easiest is, using a local repository (filesystem or embedded database), the problem with this solution is, you can lose data if you stop to deploy services on that machine without migrating the data

2- Generate a random identifier for each machine deploying your data and save it as an environment  variable, and use this variable to separate logically your retries , so in your database where you store your retry data, you add a field with this identifier, and when listing pending retries, you query only for open retries on that identifier

3-You need to implement some kind of lock solution, to make sure only one server is processing the old retries.  I dont want to implement this in the framework, because its completely up to the developer to choose the database and the strategy for doing so.

I hope it helped you.

**Comment by yarandoo** [comment]
@ericholiveira thanks for your answer.

1) and 2) are interesting options, but I think will both involve loosing data if the new instance that spins up has a new ID. Currently we have no way to manage which ID the new instance will have, or to replicate the same ID as the instance that was shut down.

3) Could be using the typical queue. Something like AWS SQS enables to have multiple consumers but only one reading the message at the time. (Visibility window). 

In this case the reading of the queue to retrieve messages should be done periodically by each instance. This could potentially work. Do you think the retry plugin could support reading from a given store periodically instead of at init time?

**Comment by ericholiveira** [comment]
First the easiest question... about the promise chain, i don't know any solution to deal with the chain... The only thing i can think as a solution for this is for you con encapsulate everything inside a service with the "retry" enabled, and make sure you handle this as a "transaction" (you have to catch exceptions on your service and cleanup any needed info), so the solution for this is check your business rule, and wrap everything you need in the retry, instead of just the access for third part.

I believe that if you decide to use a queue to do this, its better keep polling the queue in your application startup and manually calling the service again, because it is really simple to implement, and i want to avoid adding a ton of configurations on the framework, i think its going to be really confusing for most users having a option to poll for data and a option to list data.

What do you think?

**Comment by ericholiveira** [comment]
Ps: If you join the slack channel we can discuss more on the best way to solve this problem, and post the solution here

**Comment by yarandoo** [comment]
Guau, thanks for your detailed answer, sounds good!

Just one question I have is how would you handle the situation where you
have multiple instances running the application? As in this case each
instance on startup will be initializing its own studio and possibly
reading the same pending retries from the store. In this scenario I see
that your service call might be executed N times. With N being the number
of instances running.


Cheers,

**Comment by ericholiveira** [comment]
I really believe that the safest way to implement this without losing any data is to have another instance running a simple query to list all pending retries (taking into account a timeout for those in "processing" status) and make this instance call the service from other services.. you can add a simple endpoint to do it, or use studio cluster and let it find and call the services for you (or even add it to a queue and listen this queue on your instances).

I believe any other solution will add a tremendous amount of work for you to sync your instances and avoid duplication.

And as this solution is a simple read and delegate to another, you PROBABLY can scale it without any problem

Im also, working on the solution i described, and will be publishing it probably tomorrow

**Comment by ericholiveira** [comment]
@yarandoo just published the changes.. i decided to keep only the methods beforeCall and afterCall, to store your retry data, so for your problem (and anyone problem for a stateful retry) you will have to write your own logic to list your pending retries and call your service again... this should be really easy to do, as we discussed...
Let me know if you need anything else
